# filepath: d:\Projects\Chess\frontend\render.yaml
services:
  - type: web
    name: checkbro-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    # If you're using React Router or similar:
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
